Play travis
Otus-DevOps-2023-07/poskon_infra pull request #1
Opened 2023-08-11 06:49 UTC by poskon

Создана ветка play-travis
Создан шаблон PR
К репозиторию добавлен хук pre-commit
Добавлена инструкция по сборке и проверка заданий test.py

2023-08-14 07:54 UTC, mrgreyves requested changes
Здравствуйте!
Проверил ваше дз
.github/PULL_REQUEST_TEMPLATE.md - определенно не то содержимое, проверьте что вы тут положили
ДЗ возвращаю на доработку

2023-08-14 07:54 UTC, mrgreyves commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!DOCTYPE html>
Это определенно не тот файл который должен быть

2023-08-14 10:46 UTC, poskon commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!DOCTYPE html>
Исправил

2023-08-15 08:22 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все хорошо =)

2023-08-18 23:53 UTC, merged